### ISSUE TITLE
Does not compile and work with libecap-0.2.0 + squid-3.2.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [c-rack/squid-ecap-gzip#6]
```
What steps will reproduce the problem?
1. Does not work with libecap-0.2.0 + squid-3.2.3
2.
3.

What is the expected output? What do you see instead?

adapter_gzip.cc:65:32: error: 'Config' does not name a type
adapter_gzip.cc:65:40: error: ISO C++ forbids declaration of 'cfg' with no type
adapter_gzip.cc:66:34: error: 'Config' does not name a type
adapter_gzip.cc:66:42: error: ISO C++ forbids declaration of 'cfg' with no type
adapter_gzip.cc:235:40: error: 'Config' does not name a type
...

What version of the product are you using? On what operating system?

Linux Slackware + libecap-0.2.0 + squid-3.2.3 + gcc version 4.5.2 (GCC)

Please provide any additional information below.

Patch attached. Works for me.

```

Original issue reported on code.google.com by `wooltoys...@gmail.com` on 31 Oct 2012 at 9:27

Attachments:
- [squid-ecap-gzip_up_to_libecap-0.2.0.patch](https://storage.googleapis.com/google-code-attachments/squid-ecap-gzip/issue-6/comment-0/squid-ecap-gzip_up_to_libecap-0.2.0.patch)
