### ISSUE TITLE
Ubuntu 14.04 compile failure 

### ISSUE THREAD

**Issue by saneax** [c-rack/squid-ecap-gzip#12]
Compile fails with the following error message
/bin/bash ../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I../src   -g -O2 -MT adapter_gzip.lo -MD -MP -MF .deps/adapter_gzip.Tpo -c -o adapter_gzip.lo adapter_gzip.cc
 g++ -DHAVE_CONFIG_H -I../src -g -O2 -MT adapter_gzip.lo -MD -MP -MF .deps/adapter_gzip.Tpo -c adapter_gzip.cc  -fPIC -DPIC -o .libs/adapter_gzip.o
adapter_gzip.cc:74:17: error: ‘MadeXactionPointer’ in ‘class Adapter::Service’ does not name a type
         virtual Adapter::Service::MadeXactionPointer makeXaction(libecap::host::Xaction *hostx);
                 ^
adapter_gzip.cc:258:1: error: ‘MadeXactionPointer’ in ‘class Adapter::Service’ does not name a type
 Adapter::Service::MadeXactionPointer Adapter::Service::makeXaction(libecap::host::Xaction *hostx) {
 ^
adapter_gzip.cc:605:33: error: ‘RegisterVersionedService’ is not a member of ‘libecap’
 static const bool Registered = (libecap::RegisterVersionedService(new Adapter::Service));
                                 ^
adapter_gzip.cc:605:80: error: cannot allocate an object of abstract type ‘Adapter::Service’
 static const bool Registered = (libecap::RegisterVersionedService(new Adapter::Service));
                                                                                ^
adapter_gzip.cc:54:7: note:   because the following virtual functions are pure within ‘Adapter::Service’:
 class Service: public libecap::adapter::Service {
       ^
In file included from adapter_gzip.cc:45:0:
/usr/include/libecap/adapter/service.h:36:20: note:     virtual libecap::adapter::Xaction* libecap::adapter::Service::makeXaction(libecap::host::Xaction*)
   virtual Xaction *makeXaction(host::Xaction *hostx) = 0;

./Configure run https://gist.github.com/anonymous/bc8792e9a5a6ffe7af8d

**Comment by saneax** [comment]
Installed versions of squid, libecap2
https://gist.github.com/anonymous/8fe06179c10dac944d4a 
configure https://gist.github.com/anonymous/bc8792e9a5a6ffe7af8d

**Comment by c-rack** [comment]
Thanks for reporting, @saneax! Feel free to send a PR.

**Comment by c-rack** [comment]
We should modify the configure script to detect the version of ecap installed and show an error if installed version is not supported.

**Comment by saneax** [comment]
I think we are hitting issue with configure squid3.3.8 

checking for EXT_LIBECAP... no
configure: error: Package requirements (libecap >= 0.2.0 libecap < 0.3) were not met:

with the 3.3.8 squid fails to compile with ecap 1.0.0 so I am going to compile the squid 3.5.6. I Will update the outcome here.

Requested 'libecap < 0.3' but version of eCAP is 1.0.0
You may find new versions of eCAP at http://www.e-cap.org/

thanks for the quick reply.

**Comment by saneax** [comment]
Its compiled and working with libcap-1.0.0 and Squid 3.5.6. Feel free to close the issue.

**Comment by c-rack** [comment]
@saneax Thanks!
